#!/bin/bash
# read-ifs: read fields from a file
FILE=/etc/passwd
read -p "Enter a user name > " user_name
file_info=$(grep "^$user_name:" $FILE) #把grep 命令的输入结果赋值给变量file_info,grep命令使用的正则表达式确保用户名只会在/etc/passwd文件中匹配一个文本行
if [ -n "$file_info" ]; then
    IFS=":" read user pw uid gid name home shell <<< "$file_info" #一个变量赋值，一个带有一串参数的read命令，和一个奇怪的新的重定向操作符
    echo "User = '$user'"
    echo "UID = '$uid'"
    echo "GID = '$gid'"
    echo "Full Name = '$name'"
    echo "Home Dir. = '$home'"
    echo "Shell = '$shell'"
else 
    echo "No such user '$user_name'" >&2
    exit 1
fi
